org: sammyrobensparadise
app: verify-image-db
name: aws-dynamodb-starter
component: aws-dynamodb

inputs:
  deletionPolicy: delete # allows table to be removed. This property is a safe guard.
  attributeDefinitions:
    - AttributeName: ID
      AttributeType: N
    - AttributeName: Date
      AttributeType: S
  keySchema:
    - AttributeName: ID
      KeyType: RANGE
    - AttributeName: Date
      KeyType: HASH
  region: us-east-1
